name: Snyk Security Scan

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  snyk:
    name: Snyk Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'  # Change to 11 or 21 if needed

      - name: Install Snyk CLI
        run: |
          npm install -g snyk

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk test
        run: snyk test --all-projects

      - name: Run Snyk test (non-blocking)
        run: snyk test --all-projects || true
